-- Create fuzo_feed table for user-generated studio content
-- This table replaces the deprecated masterbot_posts for community-driven feed items.

CREATE TABLE IF NOT EXISTS public.fuzo_feed (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('recipe', 'video', 'photo', 'snap', 'trim')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.fuzo_feed ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Anyone can view feed items"
  ON public.fuzo_feed
  FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can post to feed"
  ON public.fuzo_feed
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_fuzo_feed_created_at ON public.fuzo_feed(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fuzo_feed_type ON public.fuzo_feed(type);
CREATE INDEX IF NOT EXISTS idx_fuzo_feed_user_id ON public.fuzo_feed(user_id);

-- Grant permissions
GRANT SELECT ON public.fuzo_feed TO anon;
GRANT ALL ON public.fuzo_feed TO authenticated;

-- Add helpful comment
COMMENT ON TABLE public.fuzo_feed IS 'Social feed content generated by users from the AI Studios (Snap, Bites, Trims)';
